# country_iso.py
# Mapping: Country name (as in your mask_legend.txt) → ISO 3166-1 alpha-2 code
# Generated from your current world map + mask (89+ countries)
# Updated: November 24, 2025

COUNTRY_TO_ISO = {
    "United States": "US",
    "Canada": "CA",
    "Mexico": "MX",
    "Brazil": "BR",
    "Argentina": "AR",
    "Greenland": "GL",
    "Iceland": "IS",
    "United Kingdom": "GB",
    "France": "FR",
    "Germany": "DE",
    "Spain": "ES",
    "Italy": "IT",
    "Russia": "RU",
    "Kazakhstan": "KZ",
    "China": "CN",
    "India": "IN",
    "Saudi Arabia": "SA",
    "Iran": "IR",
    "Turkey": "TR",
    "Egypt": "EG",
    "South Africa": "ZA",
    "Nigeria": "NG",
    "Democratic Republic of the Congo": "CD",
    "Algeria": "DZ",
    "Australia": "AU",
    "Indonesia": "ID",
    "Japan": "JP",
    "South Korea": "KR",
    "Mongolia": "MN",
    "Pakistan": "PK",
    "Afghanistan": "AF",
    "Ukraine": "UA",
    "Poland": "PL",
    "Sweden": "SE",
    "Norway": "NO",
    "New Zealand": "NZ",
    "Chile": "CL",
    "Peru": "PE",
    "Bolivia": "BO",
    "Venezuela": "VE",
    "Colombia": "CO",
    "Morocco": "MA",
    "Tunisia": "TN",
    "Libya": "LY",
    "Mauritania": "MR",
    "Sudan": "SD",
    "South Sudan": "SS",
    "Yemen": "YE",
    "Oman": "OM",
    "United Arab Emirates": "AE",
    "Qatar": "QA",
    "Bahrain": "BH",
    "Kuwait": "KW",
    "Iraq": "IQ",
    "Jordan": "JO",
    "Lebanon": "LB",
    "Syria": "SY",
    "Palestine": "PS",        # ISO code for State of Palestine
    "Djibouti": "DJ",
    "Somalia": "SO",
    "Comoros": "KM",

    # Extra ones that sometimes appear in your mask
    "Alaska (US)": "US",
    "Portugal": "PT",
    "Greece": "GR",
    "Finland": "FI",
    "Denmark": "DK",
    "Netherlands": "NL",
    "Belgium": "BE",
    "Switzerland": "CH",
    "Austria": "AT",
    "Czechia": "CZ",
    "Slovakia": "SK",
    "Hungary": "HU",
    "Romania": "RO",
    "Bulgaria": "BG",
    "Serbia": "RS",
    "Croatia": "HR",
    "Bosnia and Herzegovina": "BA",
    "Albania": "AL",
    "North Macedonia": "MK",
    "Thailand": "TH",
    "Vietnam": "VN",
    "Philippines": "PH",
    "Malaysia": "MY",
    "Myanmar": "MM",
    "Bangladesh": "BD",
    "Sri Lanka": "LK",
    "Nepal": "NP",
    "Israel": "IL",
    "Ethiopia": "ET",
    "Kenya": "KE",
    "Tanzania": "TZ",
    "Madagascar": "MG",
    "Cuba": "CU",
    "Jamaica": "JM",
    "Haiti": "HT",
    "Dominican Republic": "DO",
}

# Reverse mapping if you ever need ISO → name
ISO_TO_COUNTRY = {v: k for k, v in COUNTRY_TO_ISO.items()}

# Quick test
if __name__ == "__main__":
    print(f"Total countries mapped: {len(COUNTRY_TO_ISO)}")
    print("Tunisia →", COUNTRY_TO_ISO.get("Tunisia"))
    print("Egypt →", COUNTRY_TO_ISO.get("Egypt"))